// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"IgnisTextDatabase","status":true,"description":"Text Database v.1.0.0","parameters":{"defaultFolder":"langs","textFiles":"[\"en\"]","defaultFile":"en"}},
{"name":"GabeMZ_SmartFollowers","status":true,"description":"[v1.1.1] Changes the way followers behave for a more intelligent movement.","parameters":{"turnToward":"true","preventDiagonalClip":"true"}}
];
